---
title: "Untitled"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# PrEP Populations Estimation Tool
## User Title: `r paste(input$reportTitle, sep="")`  
## `r paste(format(Sys.Date(), "%B %d, %Y"), sep="")`

This report was generated using the PrEP Populations Estimation Tool. The tool was created as part of a partnership between the Centers for Disease Control and Prevention (CDC) and researchers at Emory University's Rollins School of Public Health. The tool applies the approach and assumptions from Smith et al (2018) [REF Forthcoming]. Users can estimate the number of individuals with PrEP indications for a specific jurisdiction by selecting that jurisdiction and using preset values for the inputs or adjusting those inputs if desired. These data are intended to be estimates and should be interpreted with caution.


## Approach and Assumptions
Smith et al applied a multiplier method based on model inputs, including 2015 HIV case surveillance data, andwith specified assumptions. First, the number of men who have sex with men (MSM) was estimated by [Grey et al. (2016)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4873305/) and updated to population estimates for 2015. The estimated number of MSM in a state was then multiplied by the national estimate of the proportion of MSM who were HIV-negative with indications for PrEP (0.247). Second, the relative proportions of new HIV diagnoses in each jurisdiction among heterosexuals (HET) compared to MSM, and among persons who inject drugs (PWID) compared to MSM were assumed to approximate the relative risk of HIV exposure for uninfected persons in each transmission risk group in a given jurisdiction. These ratios were multiplied by the number of MSM with PrEP indications to calculate the number of HET and PWID with PrEP indications in that jurisdiction. 

Lastly, to produce estimate by race/ethnicity, we used the proportion of new HIV diagnoses in each jurisdiction by race/ethnicity for each transmission risk group to approximate the relative risk of HIV exposure for uninfected persons in each transmission risk and race/ethnicity group. Within each transmission risk group, we multiplied the proportion of HIV diagnoses in 2015 among each race/ethnicity group by the number of persons with PrEP indications in that transmission risk group to calculate estimates for each transmission risk and race/ethnicity group. 


## Model Inputs
The results presented in this report are based on the following model inputs:

* The total number of MSM in the model population was set to `r paste(format(input$msmpopsize, big.mark = ","), sep = "")`
* `r paste(round(as.numeric(input$msmdiagpct, 1)), "%", sep = "")` of newly diagnosed cases were attributable to MSM, `r paste(round(as.numeric(input$hetdiagpct, 1)), "%", sep = "")` of newly diagnosed cases were attributable to HET, and `r paste(round(as.numeric(input$pwiddiagpct, 1)), "%", sep = "")` of newly diagnosed cases were attributable to PWID
* `r paste(format(round(as.numeric(input$blackmsmdiagpct), 1), big.mark = ","), "%", sep = "")` of newly diagnosed cases among MSM occurred among African-American MSM, `r paste(format(round(as.numeric(input$hispmsmdiagpct), 1), big.mark = ","), "%", sep = "")` of newly diagnosed cases among MSM occurred among Hispanic MSM, and `r paste(format(round(as.numeric(input$whitemsmdiagpct), 1), big.mark = ","), "%", sep = "")` of newly diagnosed cases among MSM occurred among White MSM

* `r paste(format(round(as.numeric(input$blackhetdiagpct), 1), big.mark = ","), "%", sep = "")` of newly diagnosed cases among HET occurred among African-American HET, `r paste(format(round(as.numeric(input$hisphetdiagpct), 1), big.mark = ","), "%", sep = "")` of newly diagnosed cases among HET occurred among Hispanic HET, and `r paste(format(round(as.numeric(input$whitehetdiagpct), 1), big.mark = ","), "%", sep = "")` of newly diagnosed cases among HET occurred among White HET

* `r paste(format(round(as.numeric(input$blackpwiddiagpct), 1), big.mark = ","), "%", sep = "")` of newly diagnosed cases among PWID occurred among African-American PWID, `r paste(format(round(as.numeric(input$hisppwiddiagpct), 1), big.mark = ","), "%", sep = "")` of newly diagnosed cases among PWID occurred among Hispanic PWID, and `r paste(format(round(as.numeric(input$whitepwiddiagpct), 1), big.mark = ","), "%", sep = "")` of newly diagnosed cases among PWID occurred among White PWID


## Results
Based on these inputs, the total number of individuals with indications for PrEP is `r paste(format(input$totalprep, big.mark = ","), sep = "")`. The estimated number of MSM  with indications for PrEP is `r paste(format(input$msmprep, big.mark = ","), sep = "")`, the estimated number of HET  with indications for PrEP is `r paste(format(input$hetprep, big.mark = ","), sep = "")`, and the estimated number of PWID  with indications for PrEP is `r paste(format(input$pwidprep, big.mark = ","), sep = "")`.

The estimated number of African-American MSM with indications for PrEP is `r paste(format(input$blackmsmprep, big.mark = ","), sep = "")`, the estimated number of Hispanic MSM with indications for PrEP is `r paste(format(input$hispmsmprep, big.mark = ","), sep = "")`, and the estimated number of White MSM  with indications for PrEP is `r paste(format(input$whitemsmprep, big.mark = ","), sep = "")`. The estimated number of African-American HET with indications for PrEP is `r paste(format(input$blackhetprep, big.mark = ","), sep = "")`, the estimated number of Hispanic HET with indications for PrEP is `r paste(format(input$hisphetprep, big.mark = ","), sep = "")`, and the estimated number of White HET with indications for PrEP is `r paste(format(input$whitehetprep, big.mark = ","), sep = "")`. The estimated number of African-American PWID with indications for PrEP is `r paste(format(input$blackpwidprep, big.mark = ","), sep = "")`, the estimated number of Hispanic PWID with indications for PrEP is `r paste(format(input$hisppwidprep, big.mark = ","), sep = "")`, and the estimated number of White PWID with indications for PrEP is `r paste(format(input$whitepwidprep, big.mark = ","), sep = "")`.

The remaining sections of this report display present the outputs from this model in tables and figures.
